### PR TITLE
Account select + Library errors resolved

### PR DESCRIPTION
**Pull request by EvolveDeveloper**

### CODE REVIEW

**Comment by wittfeldt** [comment]
I removed the custom Layout in snmp-admin and tested this branch. The account select works great, but when I navigate to any of the custom views (MibScriptField or DeviceType list dropdown) I get:

"Error: could not find react-redux context value; please ensure the component is wrapped in a <Provider>"

What do I need to change in these custom components to get it working?

**Comment by EvolveDeveloper** [comment]
Hi @wittfeldt I Tested out the same on the SNMP-Admin (master branch) flow. 
I did not run into the error you mentioned above. Could please share the steps to reproduce the following error so that I could test it ? And solve it.

My steps:
1. Comment Layout from SNMP
2. Test the Account select dropdown
3. Navigate to /device-types & test it
4. Navigate to /mibs & test it


The error in general occurs when the component that requires the value is not wrapped under the Provider that provides the value.

**Comment by wittfeldt** [comment]
Navigate to device-types or metrics list view, click right-arrow on one of the rows to reveal its custom ExpandPanel component

The MibScriptField is used in the EditMetric view, for example http://localhost:3000/#/metrics/uptime

**Review by wittfeldt — APPROVED** [review]
Nice work!

**Pull request merged**
